baseURL: "https://nikithadani.netlify.app/"
languageCode: "en-us"
title: "Nikita Thadani"
theme: "hugo-profile"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  title: "Nikita Thadani"
  description: Nikita Thadan
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Nikita."
    #subtitle: "I am looking to pursue Data Science as a career"
    content: "A passionate and hardworking young lady looking to kickstart her career at an entry level job."
    image: /images/3.JPG 
    
    button:
      enable: true
      name: "Resume"
      url: /cv.pdf
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/nikita-thadani98
        - icon: fab fa-github
          url: https://github.com/nikithadani
        - icon: fab fa-twitter
          url: https://twitter.com/NikiThadani
        - icon: fa fa-envelope
          url: mailto:nikithadani@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/head.jpg"
    content: |-
      I am a Biological Sciences graduate with a passion for coding. I have a background in Biomedical Engineering and a couple of programing languages.
      
      I am looking for a company that would be interested in my high achieving nature and my dedication to impact any organization that will find useful my motivation and desire to grow.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with:"
      items:
        - "R"
        - "HTML"
        - "Python"

  # Experience
  experience:
    enable: true
    items:
      - job: "Practicum - Department of Biomedical Engineering"
        company: "San Miguel Arcángel Hospital (Panama city, Panama)"
        companyUrl: "https://www.minsa.gob.pa/contenido/hospital-san-miguel-arcangel"
        date: "August 2019 - December 2019"
        #featuredLink:
          #enable: true
          #name: "View the project"
          #url: "https://example.com"
        content: |
          - Practiced response to service calls
          - Performed exercises for preventative maintenance procedures, and vendor management.
          - Trained  to follow procedure for calibration and repair of equipment. 
          - Learned troubleshooting techniques for various types of equipment, and electrical safety.
          
          
      - job: "Practicum - Department of Biomedical Engineering"
        company: "Hospitalar SA (Panama city, Panama)"
        companyUrl: "https://hospitalar.com.pa"
        date: "August 2018 - December 2018"
        content: |
          - Supported inventory control.
          - Assisted and observed  in minor repairs, testing, and maintenance of medical equipment.
          


          

  
  # Education
  education:
    enable: true
    # index: true
    items:
    #Rowan University
      - title: "Bachelor of Arts in Biological Sciences"
        school:
          name: "Rowan University"
          url: "https://www.rowan.edu/"
        date: "2021 - 2022"
        GPA: "3.632 out of 4.0 with Honors"
        #content: |-
        #featuredLink:
          #enable: true
          #name: "My academic record"
          #url: "https://example.com"
          
        #RCBC
      - title: "Associate of Science in Biology (Attended)"
        school:
          name: "Rowan College at Burlington County"
          url: "https://www.rcbc.edu/"
        date: "Attended 2020 - 2021"
        GPA: "3.469 out of 4.0"
        #content: |-

        #featuredLink:
          #enable: true
          #name: "My academic record"
          #url: "https://example.com"
          

      - title: "Bachelor of Science in Biomedical Engineering (Attended)"
        school:
          name: "Universidad Especializadas de las Americas (Panama City, Panama)"
          url: "http://www.udelas.ac.pa/"
        date: " Attended 2017 - 2020"
        GPA: "3.13 out of 4.0"
        #content: |-
        #featuredLink:
          #enable: true
          #name: "My academic record"
          #url: "https://example.com"
      - title: "High School"
        school:
          name: "Instituto Cultural Bilingue (Panama City, Panama)"
          url: "http://institutocultural.education/"
        #GPA: "No me acuerdo"
        #featuredLink:
          #enable: true
          #url: "https://example.com"



  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:

      - title: TidyTuesday
        content: Practicing my wrangling and data visualization skills with R.
        image: /images/projects/tidytuesday.jpg
        #featured:
          #name: Demo
          #link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/nikithadani/TidyTuesday
          - icon: fab fa-twitter
            url: https://twitter.com/NikiThadani
            

      - title: Final Project for Data Science for Biologists Fall 2021
        content: The goal was to ask FOUR scientific/explanatory questions about my dataset, and answer each question with any necessary associated wrangling, modeling, and visualization to address and/or complement the question.
        image: /images/projects/question1.png
        featured:
          name: See it here!
          link: https://nikithadani.github.io/Final-Project-for-Data-Science-for-Biologists-Fall-2021/
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/nikithadani/Final-Project-for-Data-Science-for-Biologists-Fall-2021



  #Contact
 
  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/nikithadani
      linkedin: https://www.linkedin.com/in/nikita-thadani98
      twitter: https://twitter.com/NikiThadani
      #instagram: https://instagram.com
      #facebook: https://facebook.com
 
